// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'feature/folders/models/folder.dart';
import 'feature/notes/models/note.dart';
import 'feature/tasks/models/task.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 6860182552042913652),
    name: 'Note',
    lastPropertyId: const obx_int.IdUid(15, 2754852194868257887),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4817386817861923250),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6229134873129195734),
        name: 'ulid',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(1, 1579921379446234601),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 38416890084973268),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7296137826605826059),
        name: 'contentPath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 4000350382101253665),
        name: 'tags',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 837416323830887979),
        name: 'links',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 2229329414724000291),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 5966551342573610358),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 3377055333441613179),
        name: 'folderId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(2, 65864467470878022),
        relationField: 'folder',
        relationTarget: 'Folder',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 3549072516732690778),
        name: 'isHidden',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 4920438314773740203),
        name: 'isPinned',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 4827311702158349030),
        name: 'isDeleted',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 6235253627829770802),
        name: 'colorValue',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 7046493774248128268),
        name: 'customBackgroundImage',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 2754852194868257887),
        name: 'content',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 989942441982959393),
    name: 'Folder',
    lastPropertyId: const obx_int.IdUid(4, 7747667081816772761),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8361430000973876349),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1618639552421150365),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4129226984821415488),
        name: 'parentId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7747667081816772761),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 8457444526397322708),
    name: 'Task',
    lastPropertyId: const obx_int.IdUid(7, 957742348540222657),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2135620141465990797),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 156187430093926112),
        name: 'ulid',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(3, 6970795018483787890),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6549717136243493366),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5073216522250009034),
        name: 'isCompleted',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3543433272579142769),
        name: 'dueDate',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 7870156956799161307),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 957742348540222657),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(3, 8457444526397322708),
    lastIndexId: const obx_int.IdUid(3, 6970795018483787890),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    Note: obx_int.EntityDefinition<Note>(
      model: _entities[0],
      toOneRelations: (Note object) => [object.folder],
      toManyRelations: (Note object) => {},
      getId: (Note object) => object.id,
      setId: (Note object, int id) {
        object.id = id;
      },
      objectToFB: (Note object, fb.Builder fbb) {
        final ulidOffset = fbb.writeString(object.ulid);
        final titleOffset = fbb.writeString(object.title);
        final contentPathOffset = fbb.writeString(object.contentPath);
        final tagsOffset = fbb.writeList(
          object.tags.map(fbb.writeString).toList(growable: false),
        );
        final linksOffset = fbb.writeList(
          object.links.map(fbb.writeString).toList(growable: false),
        );
        final customBackgroundImageOffset = object.customBackgroundImage == null
            ? null
            : fbb.writeString(object.customBackgroundImage!);
        final contentOffset = object.content == null
            ? null
            : fbb.writeString(object.content!);
        fbb.startTable(16);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, ulidOffset);
        fbb.addOffset(2, titleOffset);
        fbb.addOffset(3, contentPathOffset);
        fbb.addOffset(4, tagsOffset);
        fbb.addOffset(5, linksOffset);
        fbb.addInt64(6, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(7, object.updatedAt.millisecondsSinceEpoch);
        fbb.addInt64(8, object.folder.targetId);
        fbb.addBool(9, object.isHidden);
        fbb.addBool(10, object.isPinned);
        fbb.addBool(11, object.isDeleted);
        fbb.addInt64(12, object.colorValue);
        fbb.addOffset(13, customBackgroundImageOffset);
        fbb.addOffset(14, contentOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final ulidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final contentPathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final contentParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 32);
        final tagsParam = const fb.ListReader<String>(
          fb.StringReader(asciiOptimization: true),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 12, []);
        final linksParam = const fb.ListReader<String>(
          fb.StringReader(asciiOptimization: true),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 14, []);
        final isHiddenParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          22,
          false,
        );
        final isPinnedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          24,
          false,
        );
        final isDeletedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          26,
          false,
        );
        final colorValueParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          28,
        );
        final customBackgroundImageParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 30);
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0),
        );
        final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0),
        );
        final object = Note(
          id: idParam,
          ulid: ulidParam,
          title: titleParam,
          contentPath: contentPathParam,
          content: contentParam,
          tags: tagsParam,
          links: linksParam,
          isHidden: isHiddenParam,
          isPinned: isPinnedParam,
          isDeleted: isDeletedParam,
          colorValue: colorValueParam,
          customBackgroundImage: customBackgroundImageParam,
          createdAt: createdAtParam,
          updatedAt: updatedAtParam,
        );
        object.folder.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          20,
          0,
        );
        object.folder.attach(store);
        return object;
      },
    ),
    Folder: obx_int.EntityDefinition<Folder>(
      model: _entities[1],
      toOneRelations: (Folder object) => [],
      toManyRelations: (Folder object) => {},
      getId: (Folder object) => object.id,
      setId: (Folder object, int id) {
        object.id = id;
      },
      objectToFB: (Folder object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addInt64(2, object.parentId);
        fbb.addInt64(3, object.createdAt.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final parentIdParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          8,
        );
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
        );
        final object = Folder(
          id: idParam,
          name: nameParam,
          parentId: parentIdParam,
          createdAt: createdAtParam,
        );

        return object;
      },
    ),
    Task: obx_int.EntityDefinition<Task>(
      model: _entities[2],
      toOneRelations: (Task object) => [],
      toManyRelations: (Task object) => {},
      getId: (Task object) => object.id,
      setId: (Task object, int id) {
        object.id = id;
      },
      objectToFB: (Task object, fb.Builder fbb) {
        final ulidOffset = fbb.writeString(object.ulid);
        final titleOffset = fbb.writeString(object.title);
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, ulidOffset);
        fbb.addOffset(2, titleOffset);
        fbb.addBool(3, object.isCompleted);
        fbb.addInt64(4, object.dueDate?.millisecondsSinceEpoch);
        fbb.addInt64(5, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(6, object.updatedAt.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final dueDateValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          12,
        );
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final ulidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final isCompletedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          10,
          false,
        );
        final dueDateParam = dueDateValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(dueDateValue);
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0),
        );
        final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0),
        );
        final object = Task(
          id: idParam,
          ulid: ulidParam,
          title: titleParam,
          isCompleted: isCompletedParam,
          dueDate: dueDateParam,
          createdAt: createdAtParam,
          updatedAt: updatedAtParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Note] entity fields to define ObjectBox queries.
class Note_ {
  /// See [Note.id].
  static final id = obx.QueryIntegerProperty<Note>(_entities[0].properties[0]);

  /// See [Note.ulid].
  static final ulid = obx.QueryStringProperty<Note>(_entities[0].properties[1]);

  /// See [Note.title].
  static final title = obx.QueryStringProperty<Note>(
    _entities[0].properties[2],
  );

  /// See [Note.contentPath].
  static final contentPath = obx.QueryStringProperty<Note>(
    _entities[0].properties[3],
  );

  /// See [Note.tags].
  static final tags = obx.QueryStringVectorProperty<Note>(
    _entities[0].properties[4],
  );

  /// See [Note.links].
  static final links = obx.QueryStringVectorProperty<Note>(
    _entities[0].properties[5],
  );

  /// See [Note.createdAt].
  static final createdAt = obx.QueryDateProperty<Note>(
    _entities[0].properties[6],
  );

  /// See [Note.updatedAt].
  static final updatedAt = obx.QueryDateProperty<Note>(
    _entities[0].properties[7],
  );

  /// See [Note.folder].
  static final folder = obx.QueryRelationToOne<Note, Folder>(
    _entities[0].properties[8],
  );

  /// See [Note.isHidden].
  static final isHidden = obx.QueryBooleanProperty<Note>(
    _entities[0].properties[9],
  );

  /// See [Note.isPinned].
  static final isPinned = obx.QueryBooleanProperty<Note>(
    _entities[0].properties[10],
  );

  /// See [Note.isDeleted].
  static final isDeleted = obx.QueryBooleanProperty<Note>(
    _entities[0].properties[11],
  );

  /// See [Note.colorValue].
  static final colorValue = obx.QueryIntegerProperty<Note>(
    _entities[0].properties[12],
  );

  /// See [Note.customBackgroundImage].
  static final customBackgroundImage = obx.QueryStringProperty<Note>(
    _entities[0].properties[13],
  );

  /// See [Note.content].
  static final content = obx.QueryStringProperty<Note>(
    _entities[0].properties[14],
  );
}

/// [Folder] entity fields to define ObjectBox queries.
class Folder_ {
  /// See [Folder.id].
  static final id = obx.QueryIntegerProperty<Folder>(
    _entities[1].properties[0],
  );

  /// See [Folder.name].
  static final name = obx.QueryStringProperty<Folder>(
    _entities[1].properties[1],
  );

  /// See [Folder.parentId].
  static final parentId = obx.QueryIntegerProperty<Folder>(
    _entities[1].properties[2],
  );

  /// See [Folder.createdAt].
  static final createdAt = obx.QueryDateProperty<Folder>(
    _entities[1].properties[3],
  );
}

/// [Task] entity fields to define ObjectBox queries.
class Task_ {
  /// See [Task.id].
  static final id = obx.QueryIntegerProperty<Task>(_entities[2].properties[0]);

  /// See [Task.ulid].
  static final ulid = obx.QueryStringProperty<Task>(_entities[2].properties[1]);

  /// See [Task.title].
  static final title = obx.QueryStringProperty<Task>(
    _entities[2].properties[2],
  );

  /// See [Task.isCompleted].
  static final isCompleted = obx.QueryBooleanProperty<Task>(
    _entities[2].properties[3],
  );

  /// See [Task.dueDate].
  static final dueDate = obx.QueryDateProperty<Task>(
    _entities[2].properties[4],
  );

  /// See [Task.createdAt].
  static final createdAt = obx.QueryDateProperty<Task>(
    _entities[2].properties[5],
  );

  /// See [Task.updatedAt].
  static final updatedAt = obx.QueryDateProperty<Task>(
    _entities[2].properties[6],
  );
}
